// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ambbtidyplqdzjtzbwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtYmJ0aWR5cGxxZHpqdHpid2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTk2NjcsImV4cCI6MjA2Njk3NTY2N30.eKK7nvCc7ACFbL8Xe-uxhRSB6F-5Gfb61AHeTPTYw4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});